### ISSUE TITLE
Improve examples using Async::HTTP and Falcon

### ISSUE THREAD

**Issue by trevorturk** [trevorturk/async-examples#2]
Issues hit when upgrading my existing Rails app:

  - [x] `Protocol::HTTP1::BadRequest` with old VCR cassettes https://github.com/socketry/protocol-http1/issues/11
  - [x] Problematic Hop-by-hop Headers in VCR https://github.com/vcr/vcr/issues/850 [discussion created]
  - [x] VCR appending to existing cassettes when record none set: https://github.com/bblimke/webmock/pull/931

Need examples and/or documentation for the proof of concept sample apps in this repo:

  - [x] Attempting to use `async-await` but running into trouble: https://github.com/trevorturk/async-examples/pull/3
  - [x] Attempting to use `lazy_resolve` but not sure about the semaphore(s) https://github.com/trevorturk/async-examples/pull/4
  - [x] How to enable persistent http connections to multiple hosts, if possible/automatic, do we need `internet.close` (?)
  - [x] Can we use Ruby 3.0 or 3.1 when available? (IIRC Heroku doesn't support 3.0, so I'm working on 2.7 now)
  - [x] Review `rails-async-http-falcon-graphql-batch` -- is `Sync` the appropriate here? Do we need `Async::Barrier`?
  - [x] Example to replace Typhoeus#total_time, should use `Async::Clock.measure` or something manual (?)
  - [x] Example of params in a hash like https://github.com/typhoeus/typhoeus#introduction
  - [x] Docs PR re `async/http/internet/instance` https://github.com/socketry/async-http/pull/72
  - [x] Docs PR re automatic gzip handling https://github.com/socketry/async-http/pull/73 (needs help)
  - [x] How to manage preloading (I was able to use the Bundler `group :preload`, don't understand `preload.rb`)
  - [x] How to configure for Heroku, see `rack-async-http-falcon-graphql-batch` and https://github.com/socketry/falcon/issues/121#issuecomment-782382561

Feature requests:

  - [x] Merge `wait_all` re: https://github.com/socketry/async/pull/89 if/when acceptable (don't need this, can use barriers)
  - [x] Automatic support for gzip https://github.com/trevorturk/async-examples/pull/7 -> https://github.com/socketry/async-http/issues/68
  - [x] Consider adding debug logging re automatic gzip handling etc https://github.com/socketry/async-http/issues/74
  - [x] Monitor https://github.com/puma/puma/pull/2601 re: `rack-async-http-puma-graphql` (not expected to work currently?)
  - [x] Investigate `rack-async-http-falcon-graphql-dataloader` (should work in Ruby 3.1? Can we make it work now?)
  - [x] Improved handling of connection pools https://github.com/socketry/async-http/issues/67
  - [x] Add Redis support to https://github.com/socketry/async-http-cache instead of just in-memory

For the examples/documentation issues, I'd like to work in the open and/or contribute back to the relevant projects' documentation wherever possible. I'm finding the async suite of tools to be lovely, but the documentation sparse, and I'm hoping to contribute back in an effort to increase adoption. 

For the issues found while upgrading my existing Rails app, I'll need to keep that source code private, but happy to work in the open wherever possible, as illustrated by the VCR cassette issue: https://github.com/socketry/protocol-http1/issues/11 since obviously most of these concerns can be generalized.

**Comment by josh** [comment]
> Other approaches more than welcome, favorite so far is `rails-async-http-falcon-graphql-batch`

Another idea is to return `Async::Task` objects from resolvers. Then register that class with the `GraphQL::Schema`.

```ruby
class Schema < GraphQL::Schema
  query Query
  lazy_resolve Async::Task, :wait
end
```

Resolver methods can now just return an `Async::Task`:

```ruby
def one
  Async {
    response = internet.get("https://httpbin.org/delay/1").read
    JSON.parse(response)["url"]
  }
end
```

You could probably take things further by injecting something that wraps all resolvers with `Async {}` to remove that step.

This approach may mean you can avoid the graphql-batch dependency all together.

**Comment by trevorturk** [comment]
Thanks for the note, @josh -- I'll try to work up an example app using this style for reference today and report back. 

I'm also trying working up an example suggested by @ioquatix https://github.com/trevorturk/async-examples/pull/3 using `async-await` but I ran into some trouble there. I'm sure I'm just misunderstanding how this all works, but perhaps this can be a good strategy to avoid graphql batch loaders, which really shouldn't be necessary in my app's use case. (Still, I think the more examples we can provide people the better.)

**Comment by trevorturk** [comment]
@josh see https://github.com/trevorturk/async-examples/pull/4 for my attempt to implement your suggestion. The second commit doesn't work, but I'm not understanding why, but I think this seems like a good approach to avoid the batch loader which isn't really necessary in this use case with the Async::HTTP stuff.

**Comment by ioquatix** [comment]
## How to enable Accept-Encoding: gzip #7 (?) multiple headers?

We have discussed this and I think this is appropriate for default inclusion into `Async::HTTP::Internet`. See https://github.com/socketry/async-http/issues/68

**Comment by ioquatix** [comment]
We also discussed improving this: https://github.com/socketry/async-http/issues/67

**Comment by ioquatix** [comment]
>  Investigate rack-async-http-falcon-graphql-dataloader (should work in Ruby 3.1?)

Investigate how the fiber interface is supposed to be used.

**Comment by trevorturk** [comment]
I think we covered everything! I have some notes to follow up with docs re preloading and Heroku falcon.rb config once I sort those things out for myself. Thank you again for all of your help so far!
